### ISSUE TITLE
Make width and height prevalues required

### ISSUE THREAD

**Issue by bjarnef** [Offroadcode/Zoom-Area-Cropper#1]
I just noticed if width and height properties are not set in property editor configuration, then you will get broken images fro thumbnail previews. So these should probably be set to required unless there are default values which is used as fallback.

![image](https://cloud.githubusercontent.com/assets/2919859/26557299/75513068-44a0-11e7-9187-5c58ced28451.png)

![image](https://cloud.githubusercontent.com/assets/2919859/26557311/a65a4dc0-44a0-11e7-8518-ab8722e687fa.png)

**Comment by cssquirrel** [comment]
This is a good suggestion.

**Comment by cssquirrel** [comment]
Fixed in https://github.com/Offroadcode/Zoom-Area-Cropper/releases/tag/v1.0.2
